"""Initial migration.

Revision ID: 88c2f91072a1
Revises: 
Create Date: 2024-05-25 22:12:29.560560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c2f91072a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_tickets', schema=None) as batch_op:
        batch_op.drop_constraint('group_tickets_ticket_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('group_tickets_group_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ticket', ['ticket_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.drop_constraint('user_groups_group_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_groups_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_groups_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('user_groups_group_id_fkey', 'group', ['group_id'], ['id'])

    with op.batch_alter_table('group_tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group_tickets_group_id_fkey', 'group', ['group_id'], ['id'])
        batch_op.create_foreign_key('group_tickets_ticket_id_fkey', 'ticket', ['ticket_id'], ['id'])

    # ### end Alembic commands ###
